---

- name: Remove old versions
  yum:
    name:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
    - runc
    - containers-common
    - containerd.io
    state: absent

- name: Remove podman and buildah packages on CentOS 8
  yum:
    name:
    - podman
    - buildah
    state: absent
    update_cache: yes
  when: ansible_facts['distribution_major_version'] == "8"

- name: Install yum-utils package
  yum:
    name:
    - yum-utils
    update_cache: yes
    state: present

- name: Set up the stable repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    warn: false

- name: Install Docker Engine
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: Enable docker service on boot
  service:
    name: docker
    enabled: yes 

- name: Start docker service
  service:
    name: docker
    state: started

- name: Add current user to Docker group
  shell: usermod -a -G docker cloud_user

- name: Enable docker live restore
  shell: |
  cat > /etc/docker/daemon.json <<EOF
  {
    "live-restore": true
  }
  EOF

- name: Reload docker daemon
  service:
    name: docker
    state: reloaded